#!/bin/bash

###---Define Functions---###
function push_notif(){
        message=$1
        v2=$2
        v3=$3
        curl -X POST -H "Content-Type: application/json" -d '{"value1":"'"$message"'","value2":"'"$v2"'","value3":"'"$v3"'"}' https://maker.ifttt.com/trigger/Pi-IDS/with/key/XXXXXXX
}

### Calculate Subnet
subnet_part1=$(ip a | grep -o ".*\.*\.*\/.. " | grep -v inet6 | sed -e s/'inet'// -e s/" "// | awk -F '.' ' { print $1"."$2"."$3"." } ' | awk ' { print $1 } ')
subnet_part2="0"
mask=$(ip a | grep -o ".*\.*\.*\/.. " | grep -v inet6 | grep -o /..)
subnet=$subnet_part1$subnet_part2$mask

### Create Scan Folder && Get Current Date
mkdir -p /var/www/html/scans
date=$(date)

### Run Scan & Export to Report File
nmap -sn -PR $subnet -T5 | awk '/Nmap scan report for/{printf $5;printf " "$6;}/MAC Address:/{print " => "$3, $4, $5, $6;}' > /var/www/html/scans/"discovery-differential"

echo '' > /var/www/html/scans/diff.log
cat /var/www/html/scans/discovery-differential | while read line
do
	diff=$(grep "$line" /var/www/html/scans/discovery-baseline)
	if [[ $diff == '' ]]
	then
		echo "$line" >> /var/www/html/scans/diff.log
	fi
done

### Read Results & Send Push Notification(s)
cat /var/www/html/scans/diff.log | grep -v ^$ | while read diff
do
        message="New Host Detected on Network:"
        mac=$(echo $diff | awk -F ' => ' ' { print $2 } ')

        if [[ $(echo $diff | awk -F ' => ' ' { print $1 } ' | wc -l) != 1 ]]
        then
                host=$(echo $diff | awk -F ' => ' ' { print $1 } ' | awk ' { print $2 } ' | sed -e "s/(//g" -e "s/)//g")
                hostname=$(echo $diff | awk -F ' => ' ' { print $1 } ' | awk ' { print $1 } ')
        elif [[ $(echo $diff | awk -F ' => ' ' { print $1 } ' | wc -l) == 1 ]]
        then
                hostname=''  
                host=$(echo $diff | awk -F ' => ' ' { print $1 } ' | awk ' { print $1 } ' | sed -e "s/(//g" -e "s/)//g")
        fi

	# Perform Hostname Lookup If Needed
        if [[ $hostname == '' ]]
        then
                # Attempt to determine multicast/avahi/mdns hostname if no DNS name
		echo "Performing Hostname Discovery...($host)"
                hostname=$(avahi-browse -ratp | grep $host | awk -F ";" ' { print $7 } ' | uniq)
                if [[ $hostname == "()" ]] || [[ $hostname == '' ]]
                then
                        hostname='N/A'
                fi
        fi

        # Perform MAC Vendor Lookup If Needed
	if [[ $mac == '' ]]
	then
		echo "Performing MAC Vendor Lookup...($host)"
		mac=$(nmap -sn -PR -T5 $host | grep "^MAC" | sed s/"MAC Address: "//g)
	fi

        if [[ $hostname == 'N/A' ]] && [[ $mac != '' ]]
        then
                hostname="$mac"
        elif [[ $hostname != "N/A" ]] && [[ $mac != '' ]]
        then
       	        hostname="$hostname -- $mac"
	fi

	# Send Push Notification
	if [[ $host != '' ]]
	then
	        echo "Pushing $message -$host- $hostname"
	        push_notif "$message" "$host" "$hostname"
	else
	        echo "No Change..."
	fi
done
