#!/bin/bash

###---Define Functions---###
function push_notif(){
        message=$1
        v2=$2
        v3=$3
        curl -X POST -H "Content-Type: application/json" -d '{"value1":"'"$message"'","value2":"'"$v2"'","value3":"'"$v3"'"}' https://maker.ifttt.com/trigger/Pi-IDS/with/key/XXXXXXXX
}

### Calculate Subnet
subnet_part1=$(ip a | grep -o ".*\.*\.*\/.. " | grep -v inet6 | sed -e s/'inet'// -e s/" "// | awk -F '.' ' { print $1"."$2"."$3"." } ' | awk ' { print $1 } ')
subnet_part2="0"
mask=$(ip a | grep -o ".*\.*\.*\/.. " | grep -v inet6 | grep -o /..)
subnet=$subnet_part1$subnet_part2$mask

### Create Scan Folder && Get Current Date
mkdir -p /var/www/html/scans
date=$(date)

### Run Scan & Export to Report File
nmap -sn -PR $subnet -T5 -oG /var/www/html/scans/"discovery-differential" >> /dev/null

echo '' > /var/www/html/scans/diff.log
cat /var/www/html/scans/discovery-differential | grep -v ^# | while read line
do
	diff=$(grep "$line" /var/www/html/scans/discovery-baseline)	
	if [[ $diff == '' ]]
	then
		echo "$line" >> /var/www/html/scans/diff.log
	fi
done

### Read Results & Send Push Notification(s)
cat /var/www/html/scans/diff.log | grep -v ^$ | while read diff
do
	message="New Host Detected on Network:"
	host=$(echo $diff | awk ' { print $2 } ')
	hostname=$(echo $diff | awk ' { print $3 } ')

	# Perform MAC Lookup if No DNS Name
	if [[ $hostname == '()' ]]
	then
		hostname=$(nmap -sn -PR -T5 $host | grep "^MAC" | awk ' { print $3,$4 } ')
	fi
	if [[ $host != '' ]]
	then
	#       echo "Pushing $message -$host- $hostname"
	        push_notif "$message" "$host" "$hostname"
	else
	        echo "No Change..."
	fi
done
